FROM debezium/connect:2.6

USER root

# Kafka Connect plugin path already includes /kafka/connect
COPY plugins/confluentinc-kafka-connect-s3-12.0.0 /kafka/connect/confluentinc-kafka-connect-s3-12.0.0

USER kafka