services:
  # Source Database
  pgsource:
    image: postgres:14
    container_name: pgsource
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sourcepass
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical" # Directly enabling logical replication here to save a step!
    volumes:
      - pgsource_data:/var/lib/postgresql/data

  # Target Database
  pgtarget:
    image: postgres:14
    container_name: pgtarget
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: targetpass
    volumes:
      - pgtarget_data:/var/lib/postgresql/data

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # Debezium Connect
  connect:
    build:
      context: .
      dockerfile: Dockerfile.connect
    container_name: connect
    depends_on:
      - kafka
      - pgsource
      - pgtarget
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses

  minio:
    image: minio/minio:RELEASE.2020-12-26T01-35-54Z
    container_name: minio
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    restart: unless-stopped

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    depends_on:
      - kafka
      - minio
    environment:
      SPARK_MODE: master
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    volumes:
      - ./spark:/opt/spark-apps
    command: tail -f /dev/null
    ports:
      - "4040:4040"

volumes:
  pgsource_data:
  pgtarget_data:
  portainer_data:
